import { Effect } from "effect";
import { PRProposal, type FixPlan, type Hypothesis, type IssueAnalysis, type ReproductionResult, type ReviewResult, type TestVerdict } from "../domain/schemas";

const slugify = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "issue-fix";

/**
 * PRGenerator — produces a complete PR proposal (branch, commit, title,
 * body). It never pushes: the API approval endpoint performs the push +
 * `createPullRequest` after explicit user consent.
 */
export const generatePRProposal = (args: {
  analysis: IssueAnalysis;
  rootCause: Hypothesis;
  plan: FixPlan;
  reproduction: ReproductionResult;
  verdicts: readonly TestVerdict[];
  review: ReviewResult;
  diff: string;
  issueNumber: number;
}): Effect.Effect<PRProposal, never> =>
  Effect.gen(function* () {
    const { analysis, rootCause, plan, reproduction, verdicts, review, diff, issueNumber } = args;
    const short = slugify(analysis.summary);
    const branch = `fix/issue-${issueNumber}-${short}`;
    const title = `fix: ${analysis.summary.slice(0, 90)}`;

    const { additions, deletions, files } = summarizeDiff(diff);
    const tests = verdicts.map((v) => `- ${v.passed ? "PASS" : "FAIL"} \`${v.command}\` — ${v.summary}`).join("\n");

    const body = [
      `## Problem`,
      ``,
      `${analysis.summary}`,
      ``,
      `Fixes #${issueNumber}.`,
      ``,
      `## Root cause`,
      ``,
      `**${rootCause.title}**`,
      ``,
      `${rootCause.description}`,
      ``,
      `## Solution`,
      ``,
      ...plan.changes.map((c) => `- ${c}`),
      ``,
      `## Reproduction`,
      ``,
      `- Method: ${reproduction.method}`,
      `- ${reproduction.detail}`,
      ``,
      `## Tests`,
      ``,
      tests || "- (no test output captured)",
      ``,
      `## Review`,
      ``,
      `- Verdict: ${review.approved ? "APPROVED" : "CHANGES REQUESTED"} (severity: ${review.severity})`,
      `- ${review.summary}`,
      ``,
      `## Risk`,
      ``,
      `- ${plan.risk} — ${plan.expectedBehavior}`,
      ``,
      `---`,
      `Generated by Fixora. Requires human review before merge.`,
    ].join("\n");

    return new PRProposal({
      branch,
      commitMessage: `fix: ${analysis.summary.slice(0, 72)}\n\n${rootCause.title}\n\nFixes #${issueNumber}`,
      title,
      body,
      filesChanged: files,
      additions,
      deletions,
    });
  });

const summarizeDiff = (diff: string): { additions: number; deletions: number; files: string[] } => {
  let additions = 0;
  let deletions = 0;
  const files: string[] = [];
  for (const line of diff.split("\n")) {
    if (line.startsWith("+++ b/")) files.push(line.slice(6));
    else if (line.startsWith("+") && !line.startsWith("+++")) additions++;
    else if (line.startsWith("-") && !line.startsWith("---")) deletions++;
  }
  return { additions, deletions, files };
};
